<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VPKTools.Tier0\VPKTools.Tier0.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ValvePak" Version="4.0.0.142" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>VPKTools.Pak</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <BaseOutputPath>..\build\</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)Release\VPKTools.Pak</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
