<Project>
  <PropertyGroup>
    <Version>1.0.0</Version>

    <Authors>Swiftly Tracker</Authors>
    <Company>Swiftly Tracker</Company>
    <Product>VPKTools</Product>
    <Copyright>Copyright (c) Swiftly Tracker</Copyright>

    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Swiftly-Tracker/VPKTools</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Swiftly-Tracker/VPKTools</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
